package com.chinasoft.app.domain;

// Generated 2017-7-14 16:42:05 by Hibernate Tools 3.4.0.CR1

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer bookid;
	private String bookname;
	private String publicname;
	private String year;

	public Book() {
	}

	public Book(String bookname, String publicname, String year) {
		this.bookname = bookname;
		this.publicname = publicname;
		this.year = year;
	}

	public Integer getBookid() {
		return this.bookid;
	}

	public void setBookid(Integer bookid) {
		this.bookid = bookid;
	}

	public String getBookname() {
		return this.bookname;
	}

	public void setBookname(String bookname) {
		this.bookname = bookname;
	}

	public String getPublicname() {
		return this.publicname;
	}

	public void setPublicname(String publicname) {
		this.publicname = publicname;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
