package com.chinasoft.app.domain;


import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer adminId;
	private String adminName;
	private String adminPassword;
	private String job;
	private Set recordlists = new HashSet(0);

	public Admin() {
	}

	public Admin(String adminName, String adminPassword) {
		this.adminName = adminName;
		this.adminPassword = adminPassword;
	}

	public Admin(String adminName, String adminPassword, String job,
			Set recordlists) {
		this.adminName = adminName;
		this.adminPassword = adminPassword;
		this.job = job;
		this.recordlists = recordlists;
	}

	public Integer getAdminId() {
		return this.adminId;
	}

	public void setAdminId(Integer adminId) {
		this.adminId = adminId;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getAdminPassword() {
		return this.adminPassword;
	}

	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Set getRecordlists() {
		return this.recordlists;
	}

	public void setRecordlists(Set recordlists) {
		this.recordlists = recordlists;
	}

}
