package com.chinasoft.app.domain;

// Generated 2017-7-22 13:29:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand implements java.io.Serializable {

	private String bname;
	private String country;
	private Set productses = new HashSet(0);

	public Brand() {
	}

	public Brand(String BName, String country) {
		this.bname = BName;
		this.country = country;
	}

	public Brand(String BName, String country, Set productses) {
		this.bname = BName;
		this.country = country;
		this.productses = productses;
	}

	public String getBname() {
		return this.bname;
	}

	public void setBname(String BName) {
		this.bname = BName;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Set getProductses() {
		return productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}
	
}
