package com.chinasoft.app.domain;


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Integer uid;
	private String username;
	private String password;
	private String address;
	private String telephone;
	private boolean isvip;
	private String vipId;
	private Integer credit;
	private Integer degree;
	private Set orderinfos = new HashSet(0);
	private Set messageboxes = new HashSet(0);

	public Customer() {
	}

	public Customer(String username, String password, boolean isvip) {
		this.username = username;
		this.password = password;
		this.isvip = isvip;
	}

	public Customer(String username, String password, String address,
			String telephone, boolean isvip, String vipId, Integer credit,
			Integer degree, Set orderinfos, Set messageboxes) {
		this.username = username;
		this.password = password;
		this.address = address;
		this.telephone = telephone;
		this.isvip = isvip;
		this.vipId = vipId;
		this.credit = credit;
		this.degree = degree;
		this.orderinfos = orderinfos;
		this.messageboxes = messageboxes;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public boolean isIsvip() {
		return this.isvip;
	}

	public void setIsvip(boolean isvip) {
		this.isvip = isvip;
	}

	public String getVipId() {
		return this.vipId;
	}

	public void setVipId(String vipId) {
		this.vipId = vipId;
	}

	public Integer getCredit() {
		return this.credit;
	}

	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	public Integer getDegree() {
		return this.degree;
	}

	public void setDegree(Integer degree) {
		this.degree = degree;
	}

	public Set getOrderinfos() {
		return this.orderinfos;
	}

	public void setOrderinfos(Set orderinfos) {
		this.orderinfos = orderinfos;
	}

	public Set getMessageboxes() {
		return this.messageboxes;
	}

	public void setMessageboxes(Set messageboxes) {
		this.messageboxes = messageboxes;
	}

}
