package com.chinasoft.app.domain;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orderinfo generated by hbm2java
 */
public class Orderinfo implements java.io.Serializable {

	private Integer oid;
	private Customer customer;
	private Date orderTime;
	private String totalMoney;
	private Integer totalAmount;
	private Integer issure;
	private String address;
	private Set pos = new HashSet(0);

	public Orderinfo() {
	}

	public Orderinfo(Customer customer, Date orderTime, String totalMoney,
			Integer totalAmount, Integer issure, String address, Set pos) {
		this.customer = customer;
		this.orderTime = orderTime;
		this.totalMoney = totalMoney;
		this.totalAmount = totalAmount;
		this.issure = issure;
		this.address = address;
		this.pos = pos;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public String getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(String totalMoney) {
		this.totalMoney = totalMoney;
	}

	public Integer getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(Integer totalAmount) {
		this.totalAmount = totalAmount;
	}

	public Integer getIssure() {
		return this.issure;
	}

	public void setIssure(Integer issure) {
		this.issure = issure;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getPos() {
		return this.pos;
	}

	public void setPos(Set pos) {
		this.pos = pos;
	}

}
