package com.chinasoft.app.domain;


/**
 * Po generated by hbm2java
 */
public class Po implements java.io.Serializable {

	private Integer poId;
	private Orderinfo orderinfo;
	private Products products;

	public Po() {
	}

	public Po(Orderinfo orderinfo, Products products) {
		this.orderinfo = orderinfo;
		this.products = products;
	}

	public Integer getPoId() {
		return this.poId;
	}

	public void setPoId(Integer poId) {
		this.poId = poId;
	}

	public Orderinfo getOrderinfo() {
		return this.orderinfo;
	}

	public void setOrderinfo(Orderinfo orderinfo) {
		this.orderinfo = orderinfo;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

}
