package com.chinasoft.app.domain;
// Generated 2017-7-22 13:29:50 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private Integer productId;
	private Brand brand;
	private String productName;
	private String price;
	private String sendAddr;
	private String vipPrice;
	private String detailInfo;
	private String type;
	private String primecost;
	private String webPrice;
	private Integer hotLevel;
	private Integer sellAmount;
	private Set pos = new HashSet(0);
	private Set recordlists = new HashSet(0);
	private Set stores = new HashSet(0);
	private Set messageboxes = new HashSet(0);

	public Products() {
	}

	public Products(Brand brand, String productName, String price,
			String sendAddr, String vipPrice, String detailInfo, String type,
			String primecost, String webPrice, Integer hotLevel,
			Integer sellAmount, Set pos, Set recordlists, Set stores,
			Set messageboxes) {
		this.brand = brand;
		this.productName = productName;
		this.price = price;
		this.sendAddr = sendAddr;
		this.vipPrice = vipPrice;
		this.detailInfo = detailInfo;
		this.type = type;
		this.primecost = primecost;
		this.webPrice = webPrice;
		this.hotLevel = hotLevel;
		this.sellAmount = sellAmount;
		this.pos = pos;
		this.recordlists = recordlists;
		this.stores = stores;
		this.messageboxes = messageboxes;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getSendAddr() {
		return this.sendAddr;
	}

	public void setSendAddr(String sendAddr) {
		this.sendAddr = sendAddr;
	}

	public String getVipPrice() {
		return this.vipPrice;
	}

	public void setVipPrice(String vipPrice) {
		this.vipPrice = vipPrice;
	}

	public String getDetailInfo() {
		return this.detailInfo;
	}

	public void setDetailInfo(String detailInfo) {
		this.detailInfo = detailInfo;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPrimecost() {
		return this.primecost;
	}

	public void setPrimecost(String primecost) {
		this.primecost = primecost;
	}

	public String getWebPrice() {
		return this.webPrice;
	}

	public void setWebPrice(String webPrice) {
		this.webPrice = webPrice;
	}

	public Integer getHotLevel() {
		return this.hotLevel;
	}

	public void setHotLevel(Integer hotLevel) {
		this.hotLevel = hotLevel;
	}

	public Integer getSellAmount() {
		return this.sellAmount;
	}

	public void setSellAmount(Integer sellAmount) {
		this.sellAmount = sellAmount;
	}

	public Set getPos() {
		return pos;
	}

	public void setPos(Set pos) {
		this.pos = pos;
	}

	public Set getRecordlists() {
		return recordlists;
	}

	public void setRecordlists(Set recordlists) {
		this.recordlists = recordlists;
	}

	public Set getStores() {
		return stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

	public Set getMessageboxes() {
		return messageboxes;
	}

	public void setMessageboxes(Set messageboxes) {
		this.messageboxes = messageboxes;
	}
}
