package com.chinasoft.app.domain;


import java.util.Date;

/**
 * Recordlist generated by hbm2java
 */
public class Recordlist implements java.io.Serializable {

	private Integer rlId;
	private Warehouse warehouse;
	private Admin admin;
	private Products products;
	private String operationType;
	private Date operationTime;
	private Integer changeNumber;

	public Recordlist() {
	}

	public Recordlist(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	public Recordlist(Warehouse warehouse, Admin admin, Products products,
			String operationType, Date operationTime, Integer changeNumber) {
		this.warehouse = warehouse;
		this.admin = admin;
		this.products = products;
		this.operationType = operationType;
		this.operationTime = operationTime;
		this.changeNumber = changeNumber;
	}

	public Integer getRlId() {
		return this.rlId;
	}

	public void setRlId(Integer rlId) {
		this.rlId = rlId;
	}

	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	public Date getOperationTime() {
		return this.operationTime;
	}

	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	public Integer getChangeNumber() {
		return this.changeNumber;
	}

	public void setChangeNumber(Integer changeNumber) {
		this.changeNumber = changeNumber;
	}

}
