package com.chinasoft.app.domain;

// Generated 2017-7-20 16:19:33 by Hibernate Tools 3.4.0.CR1

/**
 * StoreId generated by hbm2java
 */
public class StoreId implements java.io.Serializable {

	private int productId;
	private int WId;

	public StoreId() {
	}

	public StoreId(int productId, int WId) {
		this.productId = productId;
		this.WId = WId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getWId() {
		return this.WId;
	}

	public void setWId(int WId) {
		this.WId = WId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StoreId))
			return false;
		StoreId castOther = (StoreId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getWId() == castOther.getWId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getWId();
		return result;
	}

}
