package com.chinasoft.app.domain;


/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	private Warehouse warehouse;
	private Products products;
	private Integer storeNum;

	public Store() {
	}

	public Store(Warehouse warehouse, Products products, Integer storeNum) {
		this.warehouse = warehouse;
		this.products = products;
		this.storeNum = storeNum;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Integer getStoreNum() {
		return this.storeNum;
	}

	public void setStoreNum(Integer storeNum) {
		this.storeNum = storeNum;
	}

}
