package com.chinasoft.app.domain;


import java.util.HashSet;
import java.util.Set;

/**
 * Warehouse generated by hbm2java
 */
public class Warehouse implements java.io.Serializable {

	private Integer WId;
	private String location;
	private String wareName;
	private String WPhone;
	private Set recordlists = new HashSet(0);
	private Set stores = new HashSet(0);

	public Warehouse() {
	}

	public Warehouse(String location, String wareName, String WPhone,
			Set recordlists, Set stores) {
		this.location = location;
		this.wareName = wareName;
		this.WPhone = WPhone;
		this.recordlists = recordlists;
		this.stores = stores;
	}

	public Integer getWId() {
		return this.WId;
	}

	public void setWId(Integer WId) {
		this.WId = WId;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getWareName() {
		return this.wareName;
	}

	public void setWareName(String wareName) {
		this.wareName = wareName;
	}

	public String getWPhone() {
		return this.WPhone;
	}

	public void setWPhone(String WPhone) {
		this.WPhone = WPhone;
	}

	public Set getRecordlists() {
		return this.recordlists;
	}

	public void setRecordlists(Set recordlists) {
		this.recordlists = recordlists;
	}

	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

}
